name: Test Python package

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'
      - 'src/**.py'
  workflow_dispatch:

jobs:
  setup-and-test:
    name: Set up and test Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.13', '3.14']
        os: ['windows-latest', 'windows-2022', 'macos-latest', 'ubuntu-latest']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: pip install -U hatch
      - name: Test the project
        run: hatch test -a
      - name: Install build package
        run: pip install -U build
      - name: Build Python
        run: python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "dist-(${{ matrix.os }}_py${{ matrix.python-version }})"
          path: dist/*
